import { PrismaClient } from '@prisma/client';
import { comparePassword } from '../utils/crypto';
import { JWTPayload, LoginRequest, LoginResponse } from '../types';

const prisma = new PrismaClient();

export class AuthService {
  async login(data: LoginRequest): Promise<LoginResponse | null> {
    const user = await prisma.user.findUnique({
      where: { username: data.username },
    });

    if (!user) {
      return null;
    }

    const isPasswordValid = await comparePassword(data.password, user.password);
    if (!isPasswordValid) {
      return null;
    }

    return {
      token: '', // Will be generated by JWT middleware
      user: {
        id: user.id,
        username: user.username,
        role: user.role,
      },
    };
  }

  async getUserById(userId: string) {
    return prisma.user.findUnique({
      where: { id: userId },
      select: {
        id: true,
        username: true,
        role: true,
        createdAt: true,
      },
    });
  }

  async verifyProxyToken(token: string): Promise<boolean> {
    const setting = await prisma.appSetting.findUnique({
      where: { key: 'proxy_auth_token' },
    });

    if (!setting || !setting.value) {
      return false;
    }

    return setting.value === token;
  }
}

export const authService = new AuthService();
